language: R
cache: packages
pandoc_version: 2.17.1.1

script:
- Rscript -e 'bookdown::render_book()'

deploy:
  provider: pages
  local_dir: _book
  skip_cleanup: true
  github-token: $GITHUB_PAT
  on:
    branch: main